
spring.application.name: test

job.scheduler:
  quartzProperties:
    org.quartz:
      scheduler:
        instanceId: AUTO
      jobStore:
        class: org.quartz.simpl.RAMJobStore
  retryPolicy:
    maxNumberOfJobExecutions: 2
    delayBetweenAttemptsInMs: 1000
