language: java

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

deploy:
- provider: script
  script: ./gradlew bintrayUpload
  skip_cleanup: true
  on:
    repo: hmcts/sscs-job-scheduler
    tags: true

script:
  - ./gradlew test
  - ./gradlew functional
  - ./gradlew jacocoTestReport

after_success:
  - java -cp ./codacy-coverage-reporter-assembly-latest.jar com.codacy.CodacyCoverageReporter -l Java -r build/reports/jacoco/test/jacocoTestReport.xml
  - test "$TRAVIS_BRANCH" = "master" && test "$TRAVIS_PULL_REQUEST" = "false"

env:
  global:
  - secure: dNQOK/jd9gSgv9FMs5ueyuYBEIDyI4Lr4F67BsMj7hjpaSESlalmn3bc3XZ9M167S1G7/6BEN4879llSTrNH3qOOE4GiuRomSVXDn0taKoXjfeGASq20yKZkT/HLrbuv/H/3qa6n+iY0U6pic1urr5ifdIx5ee0hzcFH6pFkBPFlH4DVrlNzzuWj/Og5dDSBBoK7tqX761objzvdN9+wQnw1QYTmCJp4gsh17Ab+9K4w7nfJ5R11UEaSTuE+TboPGtc/xFoUgIEHPz0xGpKZWWbW/bnDltPEbzk3rimv2n0KAeKy9tBQ9s8th4whmij+D5oVLm1Rx9UKIE7ZttgoRXKcrjVo0HyphTWdaQHT8FQE/ejfUkR3DMBcF01FP5gnOWSMxc3sTIT53cf1YpZrz/OaDa/Ragb0wp4VALXmbi5iI+2T//vCRtWyAKp89pRblvgguqlTNe/mJ3tt9eUYW75Ci9RcHCnTnHQIYtzIVQiLm1V9uF1PTNC8lOE7vxKEvLrPcgRc1pRSnq1JPL1cWZPfRzXojhbmjuHeAUFxWmfxEIQ4u+ZB0ypOVe6zPBYI9nATKdWdztQwNCb93NS8PqJeVX0JGk9FgmVWfO2Wcad5U452lS9SehtB0krnNQhIRHcIm5/y1t7XvWysj95fqWGr5uhAnZjkrBDAMxl0ht8=
  - secure: WUBBdssbRrxbzGUJxbCgt6OqXQl7+73+DNaVNP6wVrO+XL92H1+B9Dwu8OsAg3Nq/jWBqCgFsrobG0J59altLX99RxHhXBxkHT6cHozlFm/NmE0FeHhfzQQvD4qj/9kS2ha07AgOnk/XD1ir/WlgXHJ3IN99rSTH5NMshtRunGrXsHbfCOhu1np85nFyf4+44nw+v8A1ELadOFZ0+WmBAaOZSBAJkTp/EQ2rmcPFNJACWwBWvifh4YCYeSGvJwvdWzGQkR5I6YKObiI++cH9M3Et+f7ZzwtDoCa4zhDYKW4OEXxG5ITFxFEmWqeOTuNFGuTUs/qHI4hCtpn4mkcSIayzSSvuVbLPjwwm7uuUh5oMuAoRr6fkSksboDWxjAt2Uip9vR8PxKziSocID5dZp3xRxIMuGhgTB/933aNLnMeg8sW6W3jlLfG7oCPlJO3X4p8KXY00JjhLnpACOkJWXA38AvH4f8gvKLGHAF17NbWIWKCYSSvRelQjNyZCu+aQbbfXSA6WyMq7xYYXnhR0C5nfQgxvPr9YlEO+9TMpvXEm8DI9m5dkSeso3NwhlVhCzrOsPeIvFBBR08UifPqG3s4QG8GwWIQNry72YGNutLykyl9FyBk59bjWf6aKb34AwjvkwhIBeC+/5lAor5vzsYPjkUE7DSuyJVzAMeqgY9w=
