
spring.application.name: test
spring.config.import: "optional:configtree:/mnt/secrets/sscs/"

job.scheduler:
  autoStart: true
  quartzProperties:
    org.quartz:
      scheduler:
        instanceId: AUTO
      jobStore:
        class: org.quartz.simpl.RAMJobStore
  retryPolicy:
    maxNumberOfJobExecutions: 2
    delayBetweenAttemptsInMs: 1000
